parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server

        ### MYSQL OPTIONS
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_general_ci
        ### SQLSRV OPTIONS
#        driver: 'pdo_sqlsrv'
#        charset: UTF-8
#        default_table_options:
#            charset: UTF-8
#            collate: UTF-8

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: App\Helpers\PrefixNamingStrategy
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                #type: annotation
                #dir: '%kernel.project_dir%/src/Entity'
                type: yml
                dir: '%kernel.project_dir%/config/Entity'
                prefix: 'App\Entity'
                alias: App
