twig:
    form_themes: ['core/bootstrap_4_form_layout.html.twig']
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: ~
    date:
        format: 'd/m/Y h:i:s'
        interval_format: '%d dias'
        timezone: America/Mexico_City