App\Entity\Document:
    type: entity
    repositoryClass: App\Repository\DocumentRepository
    manyToOne:
        project:
            targetEntity: Project
            inversedBy: documents
        template:
            targetEntity: Template
    oneToMany:
        versions:
            orderBy: { 'date': 'DESC' }
            cascade: [persist]
            targetEntity: Version
            mappedBy: document
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: NONE
    fields:
        name:
            type: string
            length: 180
            nullable: false
        creationDate:
            type: datetime
    lifecycleCallbacks:
        prePersist: [ updateCreationDate ]
