App\Entity\Group:
    type: entity
    repositoryClass: App\Repository\GroupRepository
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        name:
            type: string
            length: 180
            nullable: false
        dn:
            type: string
            length: 512
            nullable: true
        description:
            type: string
            nullable: true
    lifecycleCallbacks: {  }
