App\Entity\Project:
    type: entity
    repositoryClass: App\Repository\ProjectRepository
    oneToMany:
        documents:
            orderBy: { 'creationDate': 'DESC' }
            cascade: [persist]
            targetEntity: Document
            mappedBy: project
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        name:
            type: string
            length: 180
            unique: true
            nullable: false
        description:
            type: string
            nullable: true
        settings:
            type: json
    lifecycleCallbacks: {  }
