App\Entity\Properties:
    type: mappedSuperclass
    manyToOne:
        owner:
            targetEntity: User
        group:
          targetEntity: Group
    oneToMany:
        groupsPermissions:
            targetEntity: GroupPermission
            mappedBy: properties
    fields:
        ownerPermissions:
            type: integer
            nullable: false
        otherPermissions:
            type: integer
            nullable: false