App\Entity\Properties:
    type: mappedSuperclass
    manyToOne:
        owner:
            targetEntity: User
        group:
          targetEntity: Group
        lockedBy:
            targetEntity: User
    fields:
        ownerPermissions:
            type: integer
            nullable: false
        otherPermissions:
            type: integer
            nullable: false
        groupPermissions:
            type: integer
            nullable: false
        groupsPermissions:
            type: json
            nullable: false
        lockState:
            type: boolean
            nullable: false