App\Entity\Properties:
    type: mappedSuperclass
    manyToOne:
        owner:
            targetEntity: User
        group:
          targetEntity: Group
    fields:
        ownerPermissions:
            type: integer
            nullable: false
        otherPermissions:
            type: integer
            nullable: false
        groupsPermissions:
            type: json
            nullable: false