App\Entity\Proyect:
    type: entity
    repositoryClass: App\Repository\ProyectRepository
    oneToMany:
        documents:
            orderBy: { 'creationDate': 'DESC' }
            cascade: [persist]
            targetEntity: Document
            mappedBy: proyect
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        name:
            type: string
            length: 180
            unique: true
            nullable: false
        description:
            type: string
            nullable: true
        settings:
            type: json
    lifecycleCallbacks: {  }
