App\Entity\Setting:
    type: entity
    repositoryClass: App\Repository\SettingRepository
    id:
        id:
            type: string
            id: true
            generator:
                strategy: NONE
    fields:
        entity:
            type: string
            nullable: true
        value:
            type: object
            nullable: true
    lifecycleCallbacks: {  }
