App\Entity\Template:
    type: entity
    repositoryClass: App\Repository\TemplateRepository
    manyToOne:
        file:
            targetEntity: File
            cascade: [persist]
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: NONE
    fields:
        name:
            type: string
            length: 180
            unique: false
            nullable: false
        type:
            type: string
        settings:
            type: json
    lifecycleCallbacks: {  }
