App\Entity\User:
    type: entity
    repositoryClass: App\Repository\UserRepository
    oneToMany:
        notifications:
            orderBy: { 'creationDate': 'DESC' }
            cascade: [persist]
            targetEntity: Notification
            mappedBy: user
    id:
        id:
            type: guid
            id: true
            generator:
                strategy: UUID
    fields:
        username:
            type: string
            length: 180
            unique: true
            nullable: false
        email:
            type: string
            length: 180
            unique: true
            nullable: true
        firstName:
            type: string
            length: 180
        lastName:
            type: string
            length: 180
        password:
            type: string
            unique: false
            nullable: true
    lifecycleCallbacks: {  }
