#Debug Routes
viewdebugMain:
    path: /d
    controller: App\Controller\ViewDebugController:index
test:
    path: /t
    controller: App\Controller\ViewDebugController:test
viewdebug:
    path: /d/{page}
    controller: App\Controller\ViewDebugController:index

#Authentication Routes
login:
    path: /login
    controller: App\Controller\AuthenticationController::login

selectLoginMode:
    path: /login/mode
    controller: App\Controller\AuthenticationController::selectLoginMode

logout:
    path: /logout

resource:
    path: /file/{method}/{id}
    controller: App\Controller\ResourceController::serve

#Main pages
dashboard:
    path: /
    controller: App\Controller\DashboardController::index

notifications:
    path: /
    controller: App\Controller\DashboardController::index

users:
    path: /users
    controller: App\Controller\UsersController::users

me:
    path: /user/me
    controller: App\Controller\UsersController::user

user-edit:
    path: /user/edit/{id}
    controller: App\Controller\UsersController::user

user:
    path: /user/{id}
    controller: App\Controller\UsersController::user

proyects:
    path: /proyects
    controller: App\Controller\ProyectController::index

proyect:
    path: /proyect/{id}
    controller: App\Controller\ProyectController::index

proyect-settings:
    path: /proyect/{id}/settings
    controller: App\Controller\ProyectsController::index

settings:
    path: /settings
    controller: App\Controller\SettingsController::index

settings-action:
    path: /settings/{action}
    controller: App\Controller\SettingsController::action