#Debug Routes
viewdebugMain:
    path: /d
    controller: App\Controller\ViewDebugController:index
test:
    path: /t
    controller: App\Controller\ViewDebugController:test
viewdebug:
    path: /d/{page}
    controller: App\Controller\ViewDebugController:index

#Authentication Routes
login:
    path: /login
    controller: App\Controller\AuthenticationController::login

selectLoginMode:
    path: /login/mode
    controller: App\Controller\AuthenticationController::selectLoginMode

logout:
    path: /logout

resource:
    path: /file/{method}/{id}
    controller: App\Controller\ResourceController::serve

#Main pages
dashboard:
    path: /
    controller: App\Controller\DashboardController::index

notifications:
    path: /
    controller: App\Controller\DashboardController::index

users:
    path: /users
    controller: App\Controller\UsersController::users

me:
    path: /user/me
    controller: App\Controller\UsersController::user

user-edit:
    path: /user/{id}/edit
    controller: App\Controller\UsersController::edit

user-new:
    path: /user/new
    controller: App\Controller\UsersController::new
    
user:
    path: /user/{id}
    controller: App\Controller\UsersController::user   

groups:
    path: /groups
    controller: App\Controller\GroupController::groups

group-edit:
    path: /group/{id}/edit
    controller: App\Controller\GroupController::edit

group-new:
    path: /group/new
    controller: App\Controller\GroupController::new
    
group:
    path: /group/{id}
    controller: App\Controller\GroupController::group

projects:
    path: /projects
    controller: App\Controller\ProjectController::index

project-new:
    path: /project/new
    controller: App\Controller\ProjectController::new

project:
    path: /project/{id}
    controller: App\Controller\ProjectController::project

project-edit:
    path: /project/{id}/settings
    controller: App\Controller\ProjectController::edit

templates:
    path: /templates
    controller: App\Controller\TemplateController::index

template-new:
    path: /template/new
    controller: App\Controller\TemplateController::new

template:
    path: /template/{id}
    controller: App\Controller\TemplateController::template
    
template-edit:
    path: /template/{id}/edit
    controller: App\Controller\TemplateController::edit

template-view:
    path: /template/{id}/view
    controller: App\Controller\TemplateController::editFile



document:
    path: /document/{id}
    controller: App\Controller\DocumentController::document

document-settings:
    path: /document/{id}/settings
    controller: App\Controller\DocumentController::document

version-new:
    path: /document/{id}/new
    controller: App\Controller\DocumentController::newVersion

version-view:
    path: /document/view/{id}
    controller: App\Controller\DocumentController::viewVersion
    
version-print:
    path: /document/print/{id}
    controller: App\Controller\DocumentController::printVersion

settings:
    path: /settings
    controller: App\Controller\SettingsController::index

settings-action:
    path: /settings/{action}
    controller: App\Controller\SettingsController::action

entity-lock:
    path: /lock/{entity}/{id}
    controller: App\Controller\SettingsController::lock

entity-unlock:
    path: /unlock/{entity}/{id}
    controller: App\Controller\SettingsController::unlock